version: '3.8'

services:
  # Наше Go-приложение
  ticket-app:
    build: .
    container_name: ticket-app
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy # Ждем, пока Postgres полностью запустится
      redis-db:
        condition: service_started # Ждем старта Redis
    networks:
      - ticket-network

  # База данных PostgreSQL
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ticket_aggregator
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d # Авто-накат ваших SQL таблиц
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket-network
    healthcheck: # Проверка, что база готова принимать соединения
      test: ["CMD-SHELL", "pg_isready -U postgres -d ticket_aggregator"]
      interval: 5s
      timeout: 5s

  # Быстрый кэш Redis
  redis-db:
    image: redis:7-alpine
    container_name: redis-db
    ports:
      - "6379:6379" # Стандартный порт Redis
    networks:
      - ticket-network

networks:
  ticket-network:
    name: ticket-network

# Секция описания создаваемого постоянного хранилища
volumes:
  postgres_data: