// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.14.0
// source: api/v1/tickets.proto

package ticketv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	EventTicketService_StreamAvailableTickets_FullMethodName = "/api.v1.EventTicketService/StreamAvailableTickets"
)

// EventTicketServiceClient is the client API for EventTicketService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventTicketServiceClient interface {
	// Серверный стриминг: клиент запрашивает схему зала/места, а сервер
	// пачками стримит доступные категории и свободные кресла в реальном времени
	StreamAvailableTickets(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (EventTicketService_StreamAvailableTicketsClient, error)
}

type eventTicketServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEventTicketServiceClient(cc grpc.ClientConnInterface) EventTicketServiceClient {
	return &eventTicketServiceClient{cc}
}

func (c *eventTicketServiceClient) StreamAvailableTickets(ctx context.Context, in *TicketRequest, opts ...grpc.CallOption) (EventTicketService_StreamAvailableTicketsClient, error) {
	stream, err := c.cc.NewStream(ctx, &EventTicketService_ServiceDesc.Streams[0], EventTicketService_StreamAvailableTickets_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &eventTicketServiceStreamAvailableTicketsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EventTicketService_StreamAvailableTicketsClient interface {
	Recv() (*TicketResponse, error)
	grpc.ClientStream
}

type eventTicketServiceStreamAvailableTicketsClient struct {
	grpc.ClientStream
}

func (x *eventTicketServiceStreamAvailableTicketsClient) Recv() (*TicketResponse, error) {
	m := new(TicketResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EventTicketServiceServer is the server API for EventTicketService service.
// All implementations must embed UnimplementedEventTicketServiceServer
// for forward compatibility
type EventTicketServiceServer interface {
	// Серверный стриминг: клиент запрашивает схему зала/места, а сервер
	// пачками стримит доступные категории и свободные кресла в реальном времени
	StreamAvailableTickets(*TicketRequest, EventTicketService_StreamAvailableTicketsServer) error
	mustEmbedUnimplementedEventTicketServiceServer()
}

// UnimplementedEventTicketServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEventTicketServiceServer struct {
}

func (UnimplementedEventTicketServiceServer) StreamAvailableTickets(*TicketRequest, EventTicketService_StreamAvailableTicketsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamAvailableTickets not implemented")
}
func (UnimplementedEventTicketServiceServer) mustEmbedUnimplementedEventTicketServiceServer() {}

// UnsafeEventTicketServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventTicketServiceServer will
// result in compilation errors.
type UnsafeEventTicketServiceServer interface {
	mustEmbedUnimplementedEventTicketServiceServer()
}

func RegisterEventTicketServiceServer(s grpc.ServiceRegistrar, srv EventTicketServiceServer) {
	s.RegisterService(&EventTicketService_ServiceDesc, srv)
}

func _EventTicketService_StreamAvailableTickets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TicketRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EventTicketServiceServer).StreamAvailableTickets(m, &eventTicketServiceStreamAvailableTicketsServer{stream})
}

type EventTicketService_StreamAvailableTicketsServer interface {
	Send(*TicketResponse) error
	grpc.ServerStream
}

type eventTicketServiceStreamAvailableTicketsServer struct {
	grpc.ServerStream
}

func (x *eventTicketServiceStreamAvailableTicketsServer) Send(m *TicketResponse) error {
	return x.ServerStream.SendMsg(m)
}

// EventTicketService_ServiceDesc is the grpc.ServiceDesc for EventTicketService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventTicketService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.EventTicketService",
	HandlerType: (*EventTicketServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamAvailableTickets",
			Handler:       _EventTicketService_StreamAvailableTickets_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/tickets.proto",
}
