app:
  name: "ticket-aggregator"
  version: "1.0.0"
  env: "development" # development, staging, production

http:
  port: "8080"
  timeout: "4s"
  shutdown_timeout: "5s" # Для паттерна Closer (Graceful Shutdown)

postgres:
  # Дефолтные значения
  url: "postgres://postgres:mysecretpassword@localhost:5439/ticket_aggregator?sslmode=disable"
  max_conns: 50 # Макс.число соед-ий
  min_conns: 10 # Мин. число соед-ий
  max_conn_idle_time: "15m" # Время жизни простаивающего соед-я